### ISSUE TITLE
os.Setenv is funky across goroutines

### ISSUE THREAD

**Issue by f0o** [voodooEntity/threader#4]
os.Setenv can collide in goroutines leading to re-assigned variables and duplicates.

Use exec.Command.Env Array instead.

**Comment by voodooEntity** [comment]
Ye encountered this too so i extended the threadID to the temporary env var name so it cant collide with other goroutines sinds os.env is shared upon all goroutin spawned threads. There are bad workarround for this but i think the way of creating this variable per thread is a fine ways. The variable afterwards gets normalized as a local variable in the execution command
